from django.db import models
from layer_web_map.models import LayerWebMap

# Create your models here.
class Plotter(models.Model):
    title = models.CharField(max_length=255,null=True,blank=True)
    layer_id = models.ForeignKey(LayerWebMap, on_delete=models.CASCADE, related_name='data_id',blank=True,null=True)
    area = models.CharField(max_length=255,null=True,blank=True)
    longitude_name = models.CharField(max_length=255,null=True,blank=True)
    latitude_name = models.CharField(max_length=255,null=True,blank=True)
    data_variable = models.CharField(max_length=255,null=True,blank=True)
    units = models.CharField(max_length=255,null=True,blank=True)
    cmp_name = models.CharField(max_length=255,null=True,blank=True)
    cb_tick_fmt = models.CharField(max_length=255,null=True,blank=True)
    cm_edge_values = models.CharField(max_length=255,null=True,blank=True)
    cb_ticks = models.CharField(max_length=255,null=True,blank=True)
    cb_label_pos = models.CharField(max_length=255,null=True,blank=True)
    extend = models.CharField(max_length=255,null=True,blank=True)
    contour_labels = models.CharField(max_length=255,null=True,blank=True)
    plot_style = models.CharField(max_length=255,null=True,blank=True)
    contour_lines = models.CharField(max_length=255,null=True,blank=True)
    smooth_factor = models.CharField(max_length=255,null=True,blank=True)
    colors = models.CharField(max_length=255,null=True,blank=True)
    fill_color = models.CharField(max_length=255,null=True,blank=True)
    colormap_strategy = models.CharField(max_length=255,null=True,blank=True)
    title_plot = models.CharField(max_length=255,null=True,blank=True)
    output_filename_prefix = models.CharField(max_length=255,null=True,blank=True)
    output_filename_infix = models.CharField(max_length=255,null=True,blank=True)
    output_filename_suffix = models.CharField(max_length=255,null=True,blank=True)
    output_directory = models.CharField(max_length=255,null=True,blank=True)
    overlay_grid = models.BooleanField(null=True,blank=True)
    product_label_str = models.CharField(max_length=255,null=True,blank=True)
    boundary_in_use = models.CharField(max_length=255,null=True,blank=True)
    annual_clim_label_str = models.CharField(max_length=255,null=True,blank=True)
    monthly_clim_label_str = models.CharField(max_length=255,null=True,blank=True)
    resolution = models.CharField(max_length=255,null=True,blank=True)
    proj = models.CharField(max_length=255,null=True,blank=True)
    vlat = models.CharField(max_length=255,null=True,blank=True)
    vlon = models.CharField(max_length=255,null=True,blank=True)
    u = models.CharField(max_length=255,null=True,blank=True)
    v = models.CharField(max_length=255,null=True,blank=True)
