# Generated by Django 4.2.16 on 2025-01-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webapp_product", "0004_alter_webproduct_layer_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubMenu1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "display_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content",
                    models.ManyToManyField(
                        blank=True,
                        related_name="web_products",
                        to="webapp_product.webproduct",
                    ),
                ),
            ],
        ),
    ]
