# Generated by Django 4.2.16 on 2025-01-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0004_alter_webproduct_layer_information"),
        ("main_menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubMenu1",
            new_name="MainMenu",
        ),
    ]
