# Generated by Django 4.2.16 on 2025-01-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_menu", "0002_rename_submenu1_mainmenu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainmenu",
            options={"verbose_name_plural": "Main Menu"},
        ),
    ]
