# Generated by Django 4.2.16 on 2024-09-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_download", "0004_taskdownload_retention_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdownload",
            name="update_api_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="taskdownload",
            name="update_thredds",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskdownload",
            name="update_url_thredds",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
