# Generated by Django 4.2.16 on 2024-09-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_download", "0005_taskdownload_update_api_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdownload",
            name="update_api_url",
        ),
        migrations.RemoveField(
            model_name="taskdownload",
            name="update_thredds",
        ),
        migrations.RemoveField(
            model_name="taskdownload",
            name="update_url_thredds",
        ),
    ]
