# Generated by Django 4.2.16 on 2024-09-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LayerWebMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("zoomToLayer", models.BooleanField()),
                ("url", models.CharField(max_length=255)),
                ("layer_title", models.CharField(max_length=255)),
                ("layer_type", models.CharField(max_length=255)),
                ("is_timeseries", models.BooleanField()),
                ("image_format", models.CharField(max_length=255)),
                ("layer_name", models.CharField(max_length=255)),
                ("transparent", models.BooleanField()),
                ("style", models.CharField(max_length=255)),
                ("colormin", models.CharField(max_length=255)),
                ("colormax", models.CharField(max_length=255)),
                ("abovemaxcolor", models.CharField(max_length=255)),
                ("belowmincolor", models.CharField(max_length=255)),
                ("numcolorbands", models.IntegerField(default=250)),
                ("timeIntervalStart", models.DateTimeField()),
                ("timeIntervalEnd", models.DateTimeField()),
                ("period", models.CharField(max_length=255)),
                ("opacity", models.FloatField(blank=True, null=True)),
                ("legend_url", models.CharField(max_length=255)),
            ],
        ),
    ]
