# Generated by Django 4.2.16 on 2024-09-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="colormax",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="colormin",
            field=models.IntegerField(),
        ),
    ]
