# Generated by Django 4.2.16 on 2024-09-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0002_alter_layerwebmap_colormax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="datetime_format",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="on_click_url",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="update_color",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="update_legend",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="update_transparency",
            field=models.BooleanField(null=True),
        ),
    ]
