# Generated by Django 4.2.16 on 2024-09-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0004_alter_layerwebmap_update_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="on_click_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
