# Generated by Django 4.2.16 on 2024-09-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0005_alter_layerwebmap_on_click_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="is_composite",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
