# Generated by Django 4.2.16 on 2024-09-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0006_layerwebmap_is_composite"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="chart_style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="enable_chart",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="generate_png",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
