# Generated by Django 4.2.16 on 2024-09-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0009_layerwebmap_composite_layer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="interval_step",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
