# Generated by Django 4.2.16 on 2024-09-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0010_layerwebmap_interval_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="has_specific_timestep",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="specific_timestemps",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
