# Generated by Django 4.2.16 on 2025-01-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0011_layerwebmap_has_specific_timestep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="logscale",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
