# Generated by Django 4.2.16 on 2025-01-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0012_layerwebmap_logscale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layerwebmap",
            name="colormax",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="layerwebmap",
            name="colormin",
            field=models.FloatField(),
        ),
    ]
