# Generated by Django 4.2.16 on 2025-02-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0013_alter_layerwebmap_colormax_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layerwebmap",
            old_name="generate_png",
            new_name="enable_get_map",
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="get_map_names",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="get_map_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
