# Generated by Django 4.2.16 on 2025-02-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "layer_web_map",
            "0014_rename_generate_png_layerwebmap_enable_get_map_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="layerwebmap",
            old_name="enable_chart",
            new_name="enable_chart_table",
        ),
        migrations.RenameField(
            model_name="layerwebmap",
            old_name="chart_style",
            new_name="table_url",
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="enable_chart_timeseries",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="table_variables",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="timeseries_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="timeseries_variables",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
