# Generated by Django 4.2.16 on 2025-02-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "layer_web_map",
            "0015_rename_enable_chart_layerwebmap_enable_chart_table_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="layerwebmap",
            name="table_variable_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="layerwebmap",
            name="timeseries_variable_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
