# Generated by Django 4.2.16 on 2024-09-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="bbox_type",
            field=models.CharField(default="rectangle", max_length=255),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="copyright",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="east_bound_longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="enabled",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="has_bbox",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_five_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_five_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_four_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_four_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_one_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_one_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_six_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_six_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_three_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_three_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_two_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="metadata_two_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webproduct",
            name="north_bound_latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="south_bound_latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webproduct",
            name="west_bound_longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
