# Generated by Django 4.2.16 on 2024-09-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0002_alter_layerwebmap_colormax_and_more"),
        ("webapp_product", "0002_webproduct_bbox_type_webproduct_copyright_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webproduct",
            name="layer_information",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layer_id",
                to="layer_web_map.layerwebmap",
            ),
            preserve_default=False,
        ),
    ]
