# Generated by Django 4.2.16 on 2024-09-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("layer_web_map", "0002_alter_layerwebmap_colormax_and_more"),
        ("webapp_product", "0003_webproduct_layer_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webproduct",
            name="layer_information",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layer_id",
                to="layer_web_map.layerwebmap",
            ),
        ),
    ]
